### ISSUE TITLE
double url-encoding of '=' in remote.py

### ISSUE THREAD

**Issue by cathiele** [HansBug/plantumlcli#5]
```plantumlcli``` 0.0.3 does not work with the latest plantuml docker jetty image (Version jetty-v1.2021.14) as a remote server.

the urlencoding is performed twice, so that that the  base64 "="-padding-character from the base64 encoding in ```__compress(cls, code: str)``` is converted to ```%253D``` instead of ```%3D```

I will provide a PR https://github.com/HansBug/plantumlcli/pull/6  that solves this for me. But i don't know if this solution breaks other usecases.

**Comment by HansBug** [comment]
Okay, I will take a look afterwards, thank you for your contribution 👍 .

**Comment by HansBug** [comment]
Well, can you provide an example which can produce the problem stably.

I use the verion `jetty-v1.2021.14` at local environment but nothing happened.

**Comment by HansBug** [comment]
Fine, I found that.

Actually in the former versions, this problem has been existing for long, but the versions before `1.2021` can work well with this.

**Comment by cathiele** [comment]
Do you still need a stable example to reproduce it?

**Comment by HansBug** [comment]
I think, no.

The new merge request is going to be merged. #7

**Comment by HansBug** [comment]
Released in [0.0.4](https://github.com/HansBug/plantumlcli/releases/tag/v0.0.4).

Thank you for your contribution 😸 .
